name       : libepoxy
version    : 1.5.5
release    : 7
source     :
    - https://github.com/anholt/libepoxy/releases/download/1.5.5/libepoxy-1.5.5.tar.xz : 261663db21bcc1cc232b07ea683252ee6992982276536924271535875f5b0556
license    : MIT
component  : xorg.display
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
emul32     : yes
builddeps  :
    - pkgconfig32(egl)
    - pkgconfig32(x11)
    - pkgconfig32(xorg-macros)
    - pkgconfig32(xshmfence)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
