name       : libepoxy
version    : 1.5.7
release    : 8
source     :
    - https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.7.tar.xz : 9479cc0146ffb395fdecf9bd2a5930834fd0bce490cbcc4681ffd716bb3a0763
license    : MIT
component  : xorg.display
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
emul32     : yes
builddeps  :
    - pkgconfig32(egl)
    - pkgconfig32(x11)
    - pkgconfig32(xorg-macros)
    - pkgconfig32(xshmfence)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
