name       : libepoxy
version    : 1.5.4
release    : 6
source     :
    - https://github.com/anholt/libepoxy/releases/download/1.5.4/libepoxy-1.5.4.tar.xz : 0bd2cc681dfeffdef739cb29913f8c3caa47a88a451fd2bc6e606c02997289d2
license    : MIT
component  : xorg.display
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
emul32     : yes
builddeps  :
    - pkgconfig32(egl)
    - pkgconfig32(x11)
    - pkgconfig32(xorg-macros)
    - pkgconfig32(xshmfence)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
