name       : libepoxy
version    : 1.4.3
release    : 4
source     :
    - https://github.com/anholt/libepoxy/releases/download/1.4.3/libepoxy-1.4.3.tar.xz : 0b808a06c9685a62fca34b680abb8bc7fb2fda074478e329b063c1f872b826f6
license    : MIT
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
emul32     : yes
component  : xorg.display
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xorg-macros)
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
