name       : libepoxy
version    : 1.2
release    : 1
source     :
    - https://github.com/anholt/libepoxy/archive/v1.2.tar.gz : 42c328440f60a5795835c5ec4bdfc1329e75bba16b6e22b3a87ed17e9679e8f6
license    : MIT
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(gl)
    - util-macros
setup      : |
    ./autogen.sh --prefix=/usr
build      : |
    %make
install    : |
    %make_install
