name       : libepoxy
version    : 1.5.8
release    : 10
source     :
    - https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.8.tar.xz : cf05e4901778c434aef68bb7dc01bea2bce15440c0cecb777fb446f04db6fe0d
license    : MIT
component  : xorg.display
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
emul32     : yes
builddeps  :
    - pkgconfig32(egl)
    - pkgconfig32(x11)
    - pkgconfig32(xorg-macros)
    - pkgconfig32(xshmfence)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
