name       : libepoxy
version    : 1.3.1
release    : 3
source     :
    - https://github.com/anholt/libepoxy/releases/download/v1.3.1/libepoxy-1.3.1.tar.bz2 : 1d8668b0a259c709899e1c4bab62d756d9002d546ce4f59c9665e2fc5f001a64
license    : MIT
summary    : A library for handling OpenGL function pointer management for you
description: |
    A library for handling OpenGL function pointer management for you
emul32     : yes
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig32(xshmfence)
    - util-macros
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
